# Generated by Django 3.0.5 on 2020-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCsv',
            fields=[
                ('day', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=1000000)),
            ],
        ),
    ]
